from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QMainWindow
from Pesimo import Ui_Respuesa_PEsimo
from Malo import Ui_Respuesta_Malo
from Pasable import Ui_Respuesta_Pasable
from Tivio import Ui_Respuesta_Tivio
from Ganador import Ui_Respuesta_Ganador

class Ui_Form(object):
    def setupUi(self, Form):
        self.lista_resultados = [0] * 17
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QtCore.QSize(1920, 1080))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        Form.setBaseSize(QtCore.QSize(1920, 1080))
        self.Bannerfondo = QtWidgets.QFrame(Form)
        self.Bannerfondo.setGeometry(QtCore.QRect(0, 0, 1931, 141))
        self.Bannerfondo.setStyleSheet("  background: #7C90DF;")
        self.Bannerfondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Bannerfondo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bannerfondo.setObjectName("Bannerfondo")
        self.label = QtWidgets.QLabel(self.Bannerfondo)
        self.label.setGeometry(QtCore.QRect(510, 30, 861, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")

        self.frameLog1 = QtWidgets.QLabel(Form)
        self.frameLog1.setGeometry(QtCore.QRect(350, -20, 200, 160))
        self.frameLog1.setPixmap(QtGui.QPixmap('imagenes/logo.png'))
        self.frameLog1.setScaledContents(True)
        self.frameLog1.setObjectName("frameLog1")

        self.frameLog1_2 = QtWidgets.QLabel(Form)
        self.frameLog1_2.setGeometry(QtCore.QRect(1240, 0, 200, 160))
        self.frameLog1_2.setPixmap(QtGui.QPixmap('imagenes/logo invertido.png'))
        self.frameLog1_2.setScaledContents(True)
        self.frameLog1_2.setObjectName("frameLog1_2")

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 400, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Eleccion1 = QtWidgets.QComboBox(Form)
        self.Eleccion1.setGeometry(QtCore.QRect(790, 410, 91, 31))
        self.Eleccion1.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion1.setObjectName("Eleccion1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 460, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(110, 520, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Eleccion3 = QtWidgets.QComboBox(Form)
        self.Eleccion3.setGeometry(QtCore.QRect(790, 530, 91, 31))
        self.Eleccion3.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion3.setObjectName("Eleccion3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(110, 580, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Eleccion4 = QtWidgets.QComboBox(Form)
        self.Eleccion4.setGeometry(QtCore.QRect(790, 590, 91, 31))
        self.Eleccion4.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion4.setObjectName("Eleccion4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(110, 640, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(110, 700, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Eleccion5 = QtWidgets.QComboBox(Form)
        self.Eleccion5.setGeometry(QtCore.QRect(790, 650, 91, 31))
        self.Eleccion5.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion5.setObjectName("Eleccion5")
        self.Eleccion6 = QtWidgets.QComboBox(Form)
        self.Eleccion6.setGeometry(QtCore.QRect(790, 710, 91, 31))
        self.Eleccion6.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion6.setObjectName("Eleccion6")
        self.Eleccion11 = QtWidgets.QComboBox(Form)
        self.Eleccion11.setGeometry(QtCore.QRect(1730, 470, 91, 31))
        self.Eleccion11.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion11.setObjectName("Eleccion11")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(110, 820, 621, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(1040, 470, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(1040, 410, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(1040, 530, 721, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(110, 760, 661, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Eleccion7 = QtWidgets.QComboBox(Form)
        self.Eleccion7.setGeometry(QtCore.QRect(790, 770, 91, 31))
        self.Eleccion7.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion7.setObjectName("Eleccion7")
        self.Eleccion10 = QtWidgets.QComboBox(Form)
        self.Eleccion10.setGeometry(QtCore.QRect(1730, 410, 91, 31))
        self.Eleccion10.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion10.setObjectName("Eleccion10")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(1040, 350, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.Eleccion12 = QtWidgets.QComboBox(Form)
        self.Eleccion12.setGeometry(QtCore.QRect(1730, 530, 91, 31))
        self.Eleccion12.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion12.setObjectName("Eleccion12")
        self.Eleccion8 = QtWidgets.QComboBox(Form)
        self.Eleccion8.setGeometry(QtCore.QRect(790, 830, 91, 31))
        self.Eleccion8.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion8.setObjectName("Eleccion8")
        self.Eleccion9 = QtWidgets.QComboBox(Form)
        self.Eleccion9.setGeometry(QtCore.QRect(1730, 350, 91, 31))
        self.Eleccion9.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion9.setObjectName("Eleccion9")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(1040, 590, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Eleccion13 = QtWidgets.QComboBox(Form)
        self.Eleccion13.setGeometry(QtCore.QRect(1730, 590, 91, 31))
        self.Eleccion13.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion13.setObjectName("Eleccion13")
        self.Eleccion14 = QtWidgets.QComboBox(Form)
        self.Eleccion14.setGeometry(QtCore.QRect(1730, 650, 91, 31))
        self.Eleccion14.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion14.setObjectName("Eleccion14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(1040, 650, 641, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Eleccion15 = QtWidgets.QComboBox(Form)
        self.Eleccion15.setGeometry(QtCore.QRect(1730, 710, 91, 31))
        self.Eleccion15.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion15.setObjectName("Eleccion15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(1040, 710, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(1040, 770, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.Eleccion16 = QtWidgets.QComboBox(Form)
        self.Eleccion16.setGeometry(QtCore.QRect(1730, 770, 91, 31))
        self.Eleccion16.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion16.setObjectName("Eleccion16")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(1040, 830, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.Eleccion17 = QtWidgets.QComboBox(Form)
        self.Eleccion17.setGeometry(QtCore.QRect(1730, 830, 91, 31))
        self.Eleccion17.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion17.setObjectName("Eleccion17")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(110, 220, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.Name = QtWidgets.QLineEdit(Form)
        self.Name.setGeometry(QtCore.QRect(350, 220, 311, 51))
        self.Name.setStyleSheet("border: 3px solid #7C90DF;\n""border-radius: 20px;")
        self.Name.setObjectName("Name")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(820, 960, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {"
                                      "  border: 3px solid black;"
                                      "  border-radius: 20px;"
                                      "  background-color: #7C90DF;"
                                      "  color: white;"
                                      "  font-weight: bold;"
                                      "  padding: 10px 20px;"
                                      "}"
                                      "QPushButton:hover {"
                                      "  background-color: rgba(124, 144, 223, 0.5);"
                                      "}")
        self.pushButton.setObjectName("pushButton")

        self.Eleccion2 = QtWidgets.QComboBox(Form)
        self.Eleccion2.setGeometry(QtCore.QRect(790, 460, 91, 31))
        self.Eleccion2.setStyleSheet("border: 3px solid #7C90DF;\n""")
        self.Eleccion2.setObjectName("Eleccion2")

        self.Eleccion1.setEditable(False)
        self.Eleccion1.setPlaceholderText("")
        self.Eleccion1.setObjectName("comboBox")
        self.Eleccion1.addItem("1")
        self.Eleccion1.addItem("2")
        self.Eleccion1.addItem("3")
        self.Eleccion1.addItem("4")
        self.Eleccion1.addItem("5")

        self.Eleccion2.setEditable(False)
        self.Eleccion2.setPlaceholderText("")
        self.Eleccion2.setObjectName("comboBox")
        self.Eleccion2.addItem("1")
        self.Eleccion2.addItem("2")
        self.Eleccion2.addItem("3")
        self.Eleccion2.addItem("4")
        self.Eleccion2.addItem("5")

        self.Eleccion3.setEditable(False)
        self.Eleccion3.setPlaceholderText("")
        self.Eleccion3.setObjectName("comboBox")
        self.Eleccion3.addItem("1")
        self.Eleccion3.addItem("2")
        self.Eleccion3.addItem("3")
        self.Eleccion3.addItem("4")
        self.Eleccion3.addItem("5")

        self.Eleccion4.setEditable(False)
        self.Eleccion4.setPlaceholderText("")
        self.Eleccion4.setObjectName("comboBox")
        self.Eleccion4.addItem("1")
        self.Eleccion4.addItem("2")
        self.Eleccion4.addItem("3")
        self.Eleccion4.addItem("4")
        self.Eleccion4.addItem("5")

        self.Eleccion5.setEditable(False)
        self.Eleccion5.setPlaceholderText("")
        self.Eleccion5.setObjectName("comboBox")
        self.Eleccion5.addItem("1")
        self.Eleccion5.addItem("2")
        self.Eleccion5.addItem("3")
        self.Eleccion5.addItem("4")
        self.Eleccion5.addItem("5")

        self.Eleccion6.setEditable(False)
        self.Eleccion6.setPlaceholderText("")
        self.Eleccion6.setObjectName("comboBox")
        self.Eleccion6.addItem("1")
        self.Eleccion6.addItem("2")
        self.Eleccion6.addItem("3")
        self.Eleccion6.addItem("4")
        self.Eleccion6.addItem("5")

        self.Eleccion7.setEditable(False)
        self.Eleccion7.setPlaceholderText("")
        self.Eleccion7.setObjectName("comboBox")
        self.Eleccion7.addItem("1")
        self.Eleccion7.addItem("2")
        self.Eleccion7.addItem("3")
        self.Eleccion7.addItem("4")
        self.Eleccion7.addItem("5")

        self.Eleccion8.setEditable(False)
        self.Eleccion8.setPlaceholderText("")
        self.Eleccion8.setObjectName("comboBox")
        self.Eleccion8.addItem("1")
        self.Eleccion8.addItem("2")
        self.Eleccion8.addItem("3")
        self.Eleccion8.addItem("4")
        self.Eleccion8.addItem("5")

        self.Eleccion9.setEditable(False)
        self.Eleccion9.setPlaceholderText("")
        self.Eleccion9.setObjectName("comboBox")
        self.Eleccion9.addItem("1")
        self.Eleccion9.addItem("2")
        self.Eleccion9.addItem("3")
        self.Eleccion9.addItem("4")
        self.Eleccion9.addItem("5")

        self.Eleccion10.setEditable(False)
        self.Eleccion10.setPlaceholderText("")
        self.Eleccion10.setObjectName("comboBox")
        self.Eleccion10.addItem("1")
        self.Eleccion10.addItem("2")
        self.Eleccion10.addItem("3")
        self.Eleccion10.addItem("4")
        self.Eleccion10.addItem("5")

        self.Eleccion11.setEditable(False)
        self.Eleccion11.setPlaceholderText("")
        self.Eleccion11.setObjectName("comboBox")
        self.Eleccion11.addItem("1")
        self.Eleccion11.addItem("2")
        self.Eleccion11.addItem("3")
        self.Eleccion11.addItem("4")
        self.Eleccion11.addItem("5")

        self.Eleccion12.setEditable(False)
        self.Eleccion12.setPlaceholderText("")
        self.Eleccion12.setObjectName("comboBox")
        self.Eleccion12.addItem("1")
        self.Eleccion12.addItem("2")
        self.Eleccion12.addItem("3")
        self.Eleccion12.addItem("4")
        self.Eleccion12.addItem("5")

        self.Eleccion13.setEditable(False)
        self.Eleccion13.setPlaceholderText("")
        self.Eleccion13.setObjectName("comboBox")
        self.Eleccion13.addItem("1")
        self.Eleccion13.addItem("2")
        self.Eleccion13.addItem("3")
        self.Eleccion13.addItem("4")
        self.Eleccion13.addItem("5")

        self.Eleccion14.setEditable(False)
        self.Eleccion14.setPlaceholderText("")
        self.Eleccion14.setObjectName("comboBox")
        self.Eleccion14.addItem("1")
        self.Eleccion14.addItem("2")
        self.Eleccion14.addItem("3")
        self.Eleccion14.addItem("4")
        self.Eleccion14.addItem("5")

        self.Eleccion15.setEditable(False)
        self.Eleccion15.setPlaceholderText("")
        self.Eleccion15.setObjectName("comboBox")
        self.Eleccion15.addItem("1")
        self.Eleccion15.addItem("2")
        self.Eleccion15.addItem("3")
        self.Eleccion15.addItem("4")
        self.Eleccion15.addItem("5")

        self.Eleccion16.setEditable(False)
        self.Eleccion16.setPlaceholderText("")
        self.Eleccion16.setObjectName("comboBox")
        self.Eleccion16.addItem("1")
        self.Eleccion16.addItem("2")
        self.Eleccion16.addItem("3")
        self.Eleccion16.addItem("4")
        self.Eleccion16.addItem("5")

        self.Eleccion17.setEditable(False)
        self.Eleccion17.setPlaceholderText("")
        self.Eleccion17.setObjectName("comboBox")
        self.Eleccion17.addItem("1")
        self.Eleccion17.addItem("2")
        self.Eleccion17.addItem("3")
        self.Eleccion17.addItem("4")
        self.Eleccion17.addItem("5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.Create_Answer_Vector)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Evaluación de Productos Ganadores"))
        self.label_2.setText(_translate("Form", "1)  NIVEL DE INNOVACIÓN (FACTOR SORPRESA) "))
        self.label_3.setText(_translate("Form", "2) ALCANCE DE PUBLICO "))
        self.label_4.setText(_translate("Form", "3) CUBRE NECESIDADES Y ESPECTATIVAS "))
        self.label_5.setText(_translate("Form", "4)  PRODUCTOS APTO PARA VENDER EL FACEBOOK"))
        self.label_6.setText(_translate("Form", "5) BUENA CALIFICACION EN PLATAFORMAS DE VENTAS "))
        self.label_7.setText(_translate("Form", "6) YA SE HA VENDIDO EN OTROS PAISES"))
        self.label_8.setText(_translate("Form", "8) TIENE BAJA PROBABILIDAD DE GENERAR GARANTÍAS"))
        self.label_9.setText(_translate("Form", "11) SE VENDE EN TODAS LAS TEMPORADAS DEL AÑO "))
        self.label_10.setText(_translate("Form", "10) SU TAMAÑO Y PESO ES FACIL DE ENVIAR "))
        self.label_11.setText(_translate("Form", "12) EL MATERIAL AUDIOVIDUAL Y CONTENIDO ES FACIL DE CONSEGUIR"))
        self.label_12.setText(_translate("Form", "7) SE ENCUENTRA FACILMENTE EN EL MERCADO Y ALMACENES DE CADENA "))
        self.label_13.setText(_translate("Form", "9) SE USA DE FORMA CONSTANTE "))
        self.label_14.setText(_translate("Form", "13) HAY VARIOS PROVEEDORES CON INENTARIO DISPONIBLE "))
        self.label_15.setText(_translate("Form", "14) CONECTA EMOCIONALMENTE CON EL CLIENTE Y SUS SENTIMIENTOS "))
        self.label_16.setText(_translate("Form", "15) NO TIENE MUCHA COMPETENCIA EN EL PAIS "))
        self.label_17.setText(_translate("Form", "16) SE PUEDE VENDER EN COMBO O POR CANTIDAD "))
        self.label_18.setText(_translate("Form", "17) LO PUEDEN N USAR VARIOS INTEGRANTES DE UNA FAMILIA. "))
        self.label_19.setText(_translate("Form", "Nombre del Producto:"))
        self.pushButton.setText(_translate("Form", "Puntuar Mi Producto"))

    def getComboBoxValues(self):
            # Obtener valores de ComboBox y guardarlos en self.lista_resultados
            self.lista_resultados[0] = int(self.Eleccion1.currentText())
            self.lista_resultados[1] = int(self.Eleccion2.currentText())
            self.lista_resultados[2] = int(self.Eleccion3.currentText())
            self.lista_resultados[3] = int(self.Eleccion4.currentText())
            self.lista_resultados[4] = int(self.Eleccion5.currentText())
            self.lista_resultados[5] = int(self.Eleccion6.currentText())
            self.lista_resultados[6] = int(self.Eleccion7.currentText())
            self.lista_resultados[7] = int(self.Eleccion8.currentText())
            self.lista_resultados[8] = int(self.Eleccion9.currentText())
            self.lista_resultados[9] = int(self.Eleccion10.currentText())
            self.lista_resultados[10] = int(self.Eleccion11.currentText())
            self.lista_resultados[11] = int(self.Eleccion12.currentText())
            self.lista_resultados[12] = int(self.Eleccion13.currentText())
            self.lista_resultados[13] = int(self.Eleccion14.currentText())
            self.lista_resultados[14] = int(self.Eleccion15.currentText())
            self.lista_resultados[15] = int(self.Eleccion16.currentText())
            self.lista_resultados[16] = int(self.Eleccion17.currentText())

    def Create_Answer_Vector(self):
        if self.Name.text() == "":
            QMessageBox.warning(Form, "Alerta", "No has puesto el nombre de tu producto.", QMessageBox.Ok)
        else:
            self.getComboBoxValues()
            total = sum(self.lista_resultados)

            if total < 20:
                self.RespuestaPesimo = QtWidgets.QWidget()
                respuesta_ui = Ui_Respuesa_PEsimo()
                respuesta_ui.setupUi(self.RespuestaPesimo, total)  # Pasa el valor total como argumento
                self.RespuestaPesimo.show()
            elif 20 <= total <= 40:
                self.RespuestaMalo = QtWidgets.QWidget()
                respuesta_ui = Ui_Respuesta_Malo()
                respuesta_ui.setupUi(self.RespuestaMalo,total)
                self.RespuestaMalo.show()
            elif 41 <= total <= 60:
                self.RespuestaPasable = QtWidgets.QWidget()
                respuesta_ui = Ui_Respuesta_Pasable()
                respuesta_ui.setupUi(self.RespuestaPasable,total)
                self.RespuestaPasable.show()
            elif 61 <= total <= 80:
                self.RespuestaTivio = QtWidgets.QWidget()
                respuesta_ui = Ui_Respuesta_Tivio()
                respuesta_ui.setupUi(self.RespuestaTivio,total)
                self.RespuestaTivio.show()
            elif 81 <= total <= 100:
                self.RespuestaGanador = QtWidgets.QWidget()
                respuesta_ui = Ui_Respuesta_Ganador()
                respuesta_ui.setupUi(self.RespuestaGanador,total)
                self.RespuestaGanador.show()
        Form.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
